[features]
seeds = true
skip-lint = false


[programs.localnet]
ninja_battle = "NinjaB1ttLe1111111111111111111111111111111" # replace after deploy


[registry]
url = "https://api.apr.dev"


[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"


[scripts]
build = "anchor build"
dev = "anchor test -v"
deploy = "anchor deploy"
