# docker-compose.yaml
services:
db:
image: postgres:15
environment:
POSTGRES_PASSWORD: postgres
ports: ["5432:5432"]
api:
build: ./apps/api
environment:
DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
RPC_SOLANA: https://api.mainnet-beta.solana.com
PUBLIC_BASE_URL: http://localhost
depends_on: [db]
web:
build: ./apps/webapp
ports: ["5173:5173"]
depends_on: [api]
